### ISSUE TITLE
Unable to compile on Ubuntu 18.04.4

### ISSUE THREAD

**Issue by Steve8291** [SpiderLabs/ModSecurity-apache#68]
I have installed the latest ModSecurity version 3
Now I am trying to get the apache connector set up.
I run the following:
```
./autogen.sh
./configure --with-libmodsecurity=/usr/local/modsecurity/
make
```
 Does anyone have any idea why it fails?
I am getting the following error when I run 'make':

> chmod +x build/apxs-wrapper
> build/apxs-wrapper
> /usr/share/apr-1.0/build/libtool  --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -prefer-pic -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -Wdate-time -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -pthread  -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -fPIC -O0 -I/usr/local/modsecurity//include/  -c -o src/mod_security3.lo src/mod_security3.c && touch src/mod_security3.slo
> libtool: compile:  x86_64-linux-gnu-gcc -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DLINUX -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/apache2 -I/usr/include/apr-1.0 -I/usr/include/apr-1.0 -I/usr/include -fPIC -O0 -I/usr/local/modsecurity//include/ -c src/mod_security3.c  -fPIC -DPIC -o src/.libs/mod_security3.o
> In file included from src/msc_filters.h:17:0,
>                  from src/mod_security3.h:27,
>                  from src/mod_security3.c:4:
> src/mod_security3.h:49:5: error: unknown type name ‘Rules’
>      Rules *rules_set;
>      ^~~~~
> src/mod_security3.c: In function ‘create_tx_context’:
> src/mod_security3.c:151:14: error: ‘Rules’ undeclared (first use in this function); did you mean ‘Rules_t’?
>              (Rules *)z->rules_set, unique_id, (void *)r);
>               ^~~~~
>               Rules_t
> src/mod_security3.c:151:14: note: each undeclared identifier is reported only once for each function it appears in
> src/mod_security3.c:151:21: error: expected expression before ‘)’ token
>              (Rules *)z->rules_set, unique_id, (void *)r);
>                      ^
> src/mod_security3.c:150:18: error: too few arguments to function ‘msc_new_transaction_with_id’
>          msr->t = msc_new_transaction_with_id(msc_apache->modsec,
>                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/local/modsecurity//include/modsecurity/modsecurity.h:175:0,
>                  from src/mod_security3.h:5,
>                  from src/mod_security3.c:4:
> /usr/local/modsecurity//include/modsecurity/transaction.h:635:14: note: declared here
>  Transaction *msc_new_transaction_with_id(ModSecurity *ms,
>               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/mod_security3.c:154:21: error: expected expression before ‘)’ token
>              (Rules *)z->rules_set, (void *)r);
>                      ^
> src/mod_security3.c:153:18: error: too few arguments to function ‘msc_new_transaction’
>          msr->t = msc_new_transaction(msc_apache->modsec,
>                   ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/local/modsecurity//include/modsecurity/modsecurity.h:175:0,
>                  from src/mod_security3.h:5,
>                  from src/mod_security3.c:4:
> /usr/local/modsecurity//include/modsecurity/transaction.h:631:14: note: declared here
>  Transaction *msc_new_transaction(ModSecurity *ms,
>               ^~~~~~~~~~~~~~~~~~~
> apxs:Error: Command failed with rc=65536
> .
> Makefile:635: recipe for target 'all' failed
> make: *** [all] Error 1

**Comment by zimmerle** [comment]
The apache connector is not currently compatible with libModSecurity v3/master. Please use v3.0.3 instead. Keep in mind that the Apache connector is not yet production-ready.

**Comment by Steve8291** [comment]
@zimmerle I didn't realize that. Thank you.
